---
  -
    name: Install Kubernetes 
    hosts: m-node1
    tasks:
#------------------------------------------------#
#                                                #
#         Network and Security                   #
#                                                #
# - Edit /etc/hosts file                         #
# - Modify selinux (enforcing -> permissive)     #
# - Add ports to firewall                        #
#                                                #
#------------------------------------------------#
    - name: Updating /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 172.16.0.109 w-node1.kubtest.com w-node1
        - 172.16.0.110 w-node2.kubtest.com w-node2
        - 172.16.0.111 m-node1.kubtest.com m-node1
    - name: Updating /etc/sysctl.d/k8s.conf file
      tags: k8s_conf
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: "{{ item }}"
      with_items:
        - net.bridge.bridge-nf-call-ip6tables = 1
        - net.bridge.bridge-nf-call-iptables = 1
    - name: Check net.bridge.bridge-nf-call-iptables
      tags: sysctl_reload
      command: sysctl -n net.bridge.bridge-nf-call-ip6tables
      register: x_status
    - debug:
        msg: "{{ s_status.stdout }}"
#        vars: x_status.stdout
    - name: Reload sysctl
      tags: sysctl_reload1
      command: sysctl --system
      when: x_status.stdout != 1    
    - name: Changing selinux in Permisive mode
      selinux:
        state: permissive
        policy: targeted
    - name: Adding ports to firewalld
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items:
        - 6443/tcp
        - 2379-2380/tcp
        - 10250-10252/tcp
        - 10255/tcp
        - 6783/tcp
        - 6783-6784/udp
#------------------------------------------------#
#                                                #
#              Install Packages                  #
#                                                #
# - Add docker repository                        #
# - Add kubernetes repository                    #
# - Install docker-ce                            #
# - Install kubernetes                           #
# - Install required packages                    #
#                                                #
#------------------------------------------------#
    - name: Add docker repository
      tags:
        - add_docker_repo
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        enabled: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
    - name: Add kubernetes repository
      tags:
        - add_kubernetes_repo
      yum_repository:
        name: kubernetes
        description: Kubernetes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64 
        gpgcheck: yes
        enabled: yes
        repo_gpgcheck: yes
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        exclude:
          - kubeadm
          - kubectl
          - kubelet
    - name: Update OS
      tags: 
        - update_os
      dnf:
        name: "*"
        state: latest 
    - name: Install docker-ce
      tags:
        - i_docker
      dnf:
        name: 
          - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
          - docker-ce
        state: present
        disable_gpg_check: yes
    - name: Install kubernetes
      tags: i_kubernetes
      dnf:
        name:
          - kubelet 
          - kubeadm
          - kubectl
        disable_excludes: kubernetes
    - name: Install required packages
      tags: i_others
      dnf:
        name:
          - bash-completion
        state: present
#------------------------------------------------#
#                                                #
#              Start/Enable Services             #
#                                                #
# - Start/enable docker service                  #
# - Start/enable kubelet service                 #
#                                                #
#------------------------------------------------#
    - name: Start Services
      tags:
        - start_services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: True 
      with_items:
        - docker.service
        - kubelet.service
    - name: Check for selinux policy
      command: getenforce
      register: selinux_status
    - name: Reboot...
      tags: reboot
      reboot:
      when: selinux_status.stdout != "Permissive"
    - name: Wait to start 
      wait_for:
        timeout: 180
        port: 22
        delay: 10 
    - name: Test
      command: echo test...
  
##################### Start Services #######################

    - name: Run "swapoff -a" command
      tags:
        - swapoff
      command: swapoff -a
##################### Reboot #######################







