-
  name: Node lara dosya guncelleme
  hosts: worker_nodes
  tasks:
    - name: deneme.txt dosyasi guncelleme
      lineinfile:
#       insertbefore:
#       insertafter:
#       regexp:
        path: /tmp/deneme.txt
        line: 'ehuuuu ehuuuu'
