-
  name: Install required packages
  hosts: localhost
  tasks:
    -
      yum: name="{{ item }}" state=present
      with_items:
        - httpd
        - binutils
        - glibc
        - ksh
        - libaio
        - libXext
        - gcc
        - make
        - sysstat
        - unixODBC
        - mongodb
        - nodejs
        - grunt

