-
  name: Node lara dosya guncelleme
  hosts: worker_nodes
  tasks:
    - name: deneme.txt dosyasi guncelleme
      lineinfile:
#       insertbefore:
#       insertafter:
        regexp: 'ehu'
        state: present
        path: /tmp/deneme.txt
        line: 'ehuuu ehuuu behuu'
