-
  name: install elinks
  hosts: all_nodes
  tasks:
    - name: app-node1 paket yukleme
      yum:
        name: elinks
        state: present
      when:
        ansible_host == "app-node1.uasis.org" or
        ansible_host == "app-node2.uasis.org"

