-
  name: Node lara dosya guncelleme
  hosts: worker_nodes
  tasks:
    - name: deneme.txt dosyasi guncelleme
      lineinfile:
        insertbefore: 'behuu'
#       insertafter:
        regexp: 'behu'
        path: /tmp/deneme.txt
        line: 'tehuu'
